# Font
cursor-style = bar
cursor-style-blink = false

font-family = JetBrainsMono Nerd Font Mono
font-size = 14
font-thicken = true
adjust-cell-width = -1

# Window padding
window-padding-x = 10
window-padding-y = 10

# Machine-local overrides
config-file = ?~/.config/ghostty/local.conf
